services:
  # Caddy
  caddy:
    extends:
      file: ./caddy/compose.yml
      service: caddy
  
  # Seafile
  db:
    extends:
      file: ./seafile/compose.yml
      service: db
  memcached:
    extends:
      file: ./seafile/compose.yml
      service: memcached
  elasticsearch:
    extends:
      file: ./seafile/compose.yml
      service: elasticsearch
  seafile:
    extends:
      file: ./seafile/compose.yml
      service: seafile

  # actual
  actual:
    extends:
      file: ./actual/compose.yml
      service: actual_server

  # vaultwarden
  vaultwarden:
    extends:
      file: ./vaultwarden/compose.yml
      service: vaultwarden


networks:
  proxy:
    name: caddy_network
    driver: bridge


volumes:
  caddy_data:
  caddy_config:
