services:
  vaultwarden:
    image: vaultwarden/server:1.32.7
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      DOMAIN: "https://vw.liljeros.cloud"
      ADMIN_TOKEN: "${VW_ADMIN_TOKEN:?Vaultwarden admin token should be defined}"
    volumes:
      - ./data/:/data/
    networks:
      - proxy

networks:
  proxy:
    external: true