services:
  actual_server:
    container_name: actual
    image: docker.io/actualbudget/actual-server:latest
    volumes:
      - /opt/liljeros-cloud/actual/data:/data
    healthcheck:
      test: ["CMD-SHELL", "node src/scripts/health-check.js"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 20s
    restart: unless-stopped
    networks:
      - proxy
      
networks:
  proxy:
    external: true